# URL and Token

url: https://nirmala.infoglobal.id/api/v3
header:
  Authorization: Basic YXBpa2V5OjU3YjQ1OGNlNjhiZGE2N2Q2M2IyNzkyZmE4YjdkMDkyMjQyNzEzMDQ4MjFmNjJhYzk3YmY4YjUzMTE3ZTc5NTg=
#  Authorization: Basic YXBpa2V5OmRhYzZlZDQzZmI0Yzc4MWE3MWQ0OTE4MThjNTk5NTRhNjJhODljMzE4MmRlMzdmZjFiODk2YmY2MWFjZTlmZTQ=
